version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "dependencies"
      - "npm"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: auto
    reviewers:
      - "Vogaeael"
    target-branch: "master"
